### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by henryaddison** [openactive/openactive-test-suite#56]
As well as exercising more flows of a booking system, these will also help to cover the new features added by #50 & #52.

The subissues for the extra tests are:

- [ ] Add core/opportunity-feed tests #67
- [ ] Add core/availability-check tests #68
- [ ] Add core/simple-book-free-opportunities tests #69
- [ ] Add payment/simple-book-with-payment tests #70
- [ ] Add payment/payment-reconciliation-detail-validation tests #71
- [ ] Add restriction/booking-window tests #72
- [ ] Add cancellation/order-deletion tests #73
- [ ] Add cancellation/customer-requested-cancellation tests #74
- [ ] Add cancellation/seller-requested-cancellation tests #75
- [ ] Add details-capture/attendee-details-capture-without-payment tests #76

Depends on:
- Re-organizing the folder structure [#57]
- Support for testing non-implement feautures [#50] will be required to add every test
- Some tests will require more options over selection of a random event from feed for a test based on desired criteria of the event e.g. non-bookable opportunity, event with startDate in range of validFromBefore. Currently can only filter based on type of event but #77 should fix this.

Subtasks: 
- Add all the tests defined by the subissues above
- Document which events should be in the feed already for the tests to work [#78]
